### ISSUE TITLE
Support for Multiple Channels in th_affine2d

### ISSUE THREAD

**Issue by fizzxed** [ncullen93/torchsample#12] opened 2017-05-03 06:57 UTC
There seems to be a bug in the affine transform
```>>> import torch
>>> from torchsample.utils import *
>>> x = torch.zeros(2,1000,1000)
>>> x[:,100:1500,100:500] = 10
>>> matrix = torch.FloatTensor([[1.,0,-50],[0,1.,-50]])
>>> xb = th_affine2d(x, matrix, mode='bilinear')
```
Throws
`RuntimeError: size '[2 x 1000 x 1000]' is invalid for input of with 1000000 elements at /Users/soumith/miniconda2/conda-bld/pytorch_1490983457972/work/torch/lib/TH/THStorage.c:59`
It's attempting to view the tensor with the wrong dimensions in both `th_nearest_interp2d` and `th_bilinear_interp2d`

**Comment by ncullen93** [comment] 2017-05-03 13:29
hey it's because the current version only supports a single channel. Let me add support for that right now and get back to you

**Comment by fizzxed** [comment] 2017-05-03 18:10
Now there is another issue.
In `th_affine2d` we assume matrix has dimensions (2, 3) seen:
```
if matrix.dim() == 2:
    matrix = matrix.view(-1,2,3)
```
But in the affine transforms the matrix has size (3, 3)

**Comment by ncullen93** [comment] 2017-05-03 18:57
should be fixed... lol i desperately need to write some tests, sorry.

**Comment by bfortuner** [comment] 2017-05-03 19:09
Haven't looked closely, but having trouble with both Pad() and Rotate() passing in a tensor (3,256,256) which works for the other transform types..

Here's the rotate error I see:

`/torchsample/utils.py in th_affine2d(x, matrix, mode, center)
---> 86     if matrix.dim() == 2:
     87         matrix = matrix[:2,:]
     88         matrix = matrix.view(-1,2,3)

RuntimeError: size '[-1 x 2 x 3]' is invalid for input of with 9 elements at /py/conda-bld/pytorch_1490980628440/work/torch/lib/TH/THStorage.c:55`

**Comment by ncullen93** [comment] 2017-05-03 19:29
Sorry I'm not sure what the issue is. These all work for me:
```python
from torchsample.transforms import *
import torch as th
x = th.ones(3,256,256)
xr = Rotate(10)(x)
xs = Shear(0.1)(x)
xz = Zoom((0.8,1.2))(x)
xp = Pad((3,300,300))(x)
print(xp.size()) # torch.Size([3, 300, 300])
```

**Comment by bfortuner** [comment] 2017-05-03 23:42
This works! I was "slicing" my tensor with narrow() to remove an extra dimension, but I wasn't doing it right. Thanks

**Comment by ncullen93** [comment] 2017-05-03 23:59
Great!

**Closed by ncullen93** 2017-05-03 23:59 UTC
